// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrA7mxV5O0YkaC175_Md4fpInxeSCp0O0',
    appId: '1:146119342626:web:d76d07f4aadaae3c59a87b',
    messagingSenderId: '146119342626',
    projectId: 'feastfolio-3f2f6',
    authDomain: 'feastfolio-3f2f6.firebaseapp.com',
    storageBucket: 'feastfolio-3f2f6.firebasestorage.app',
    measurementId: 'G-CEPCQD6ZG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBguszJOLo64_SZt0y5gY-D3HpKJBSj0DE',
    appId: '1:146119342626:android:8609e192bba30d0b59a87b',
    messagingSenderId: '146119342626',
    projectId: 'feastfolio-3f2f6',
    storageBucket: 'feastfolio-3f2f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCONbS6jblUVtsCpV69Te6jnfH1cvwnpEI',
    appId: '1:146119342626:ios:3d4f32accd3c2aba59a87b',
    messagingSenderId: '146119342626',
    projectId: 'feastfolio-3f2f6',
    storageBucket: 'feastfolio-3f2f6.firebasestorage.app',
    iosBundleId: 'com.example.feastfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCONbS6jblUVtsCpV69Te6jnfH1cvwnpEI',
    appId: '1:146119342626:ios:3d4f32accd3c2aba59a87b',
    messagingSenderId: '146119342626',
    projectId: 'feastfolio-3f2f6',
    storageBucket: 'feastfolio-3f2f6.firebasestorage.app',
    iosBundleId: 'com.example.feastfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrA7mxV5O0YkaC175_Md4fpInxeSCp0O0',
    appId: '1:146119342626:web:5a55081834a1a26359a87b',
    messagingSenderId: '146119342626',
    projectId: 'feastfolio-3f2f6',
    authDomain: 'feastfolio-3f2f6.firebaseapp.com',
    storageBucket: 'feastfolio-3f2f6.firebasestorage.app',
    measurementId: 'G-9P7VXJCT0Z',
  );

}